### ISSUE TITLE
PF

### ISSUE THREAD

**Issue by moniyama** [renatinhafront/SAP012-text-analyzer#3]
Parabéns! Está com todas funcionalidades, bem implementado! Já trabalhou com branches e pull requests! <3

Conversamos sobre:
- Aplicar Protótipo 
- Melhorias em detalhes de design
- Melhorias nas Mensagens de commits
- Melhorias no HTML
- Tipos de dados de primitivos

**Comment by renatinhafront** [comment]
Executado as melhorias no design;
No ultimo commit fiz o comentário de acordo com o que foi alterado;
HTML fiz a revisão conforme solicitado;
